project:
  type: website

website:
  title: "MichaelZspace"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  
  page-footer: "© 2025 Welcome to MY COZY SPACE"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

metadata-files: 
  - _publish.yml



